name: Build and Deploy API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore mtHopeApiProject/mtHopeApiProject.sln

      - name: Build
        run: dotnet build --configuration Release mtHopeApiProject/mtHopeApiProject.sln

      - name: Deploy to Azure
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_WEBAPP_PACKAGE_PATH: '.'
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
        run: |
          # Use Azure CLI or another deploy method here to publish the API to Azure
