name: Build and deploy .NET Core application to Azure App Service

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: mtHopeApiProject20241204002211
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: MtHopeResourceGroup
  AZURE_APIM_SERVICENAME: mtHopeApiProjectapi
  AZURE_APIM_API_ID: mtHopeApiProject
  AZURE_APIM_APPSERVICEURL: https://mthopeapiproject20241204002211.azurewebsites.net
  SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 5.6.3
  SWASHBUCKLE_DOTNET_CORE_VERSION: 3.1.x
  API_IMPORT_SPECIFICATION_PATH: ./publish/swagger.json
  API_IMPORT_DLL: ./mtHopeApiProject/bin/Release/net9.0/mtHopeApiProject.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: .

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore mtHopeApiOnlySolution.sln

      - name: Build
        run: dotnet build mtHopeApiOnlySolution.sln --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test mtHopeApiOnlySolution.sln --no-build

      - name: Publish
        run: dotnet publish mtHopeApiOnlySolution.sln --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI .NET Global Tool
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

      - name: Generate Open API Specification Document
        run: swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" "
